/**
 * Author: Jorge Santana
 * Description: test writing/reading of tickets generated by another app 
 */

void main() {
  /**
   * Generate ticket json from ticket object
   */

  /**
   * Generate ticket object from ticket json
   */

  /**
   * Ensure original ticket object is equals to gotten ticket object
   */

  /**
   * Ensure original ticket json is equals to gotten ticket json
   * 
   */

  /**
   * Generate ticket QR from ticket object
   */

  /**
   * Generate ticket object from ticket QR
   */
}
